### ISSUE TITLE
Add Normal Map as secondary texture to Sprites

### ISSUE THREAD

**Issue by BauRawson** [Seanba/SuperTiled2Unity#104]
Hello!

First of all, I want to say thanks because this importer is awesome.

We are currently working on a 2D game that relies on Unity's Lightweight Render Pipeline (LWRP) to cast lights on Sprites, and take advantage of the NormalMaps added to create a nice effect. (Tutorial here: https://docs.unity3d.com/Manual/SpriteEditor-SecondaryTextures.html)

What I'm trying to do now is to add the NormalMap to the Sprites I use for the tilemap, but it does not work as expected.

What I think happens is, when importing, SuperTiled2Unity creates it's own Sprite for the tiles, and I should add the Secondary Texture to that Sprite class.

Is this correct? If so, would you mind pointing the part of the code or the class where this happens? I don't mind coding it myself, but it is hard for me to dive into the code to see where it happens.

Also, I'm guessing I should disable the create Atlas option to do this, is that right?

**Comment by Seanba** [comment]
Hi there, @BauRawson. Sorry the late reply.

Unfortunately, `Secondary Textures` are not supported yet for the `TilemapRenderer`. However, you can accomplish what you're looking for through some extra management of your textures and materials using the new `Material Matching` feature that was just added to SuperTiled2Unity version 1.8.0.

I've made a repository with a working example of a normal map being used and some notes on how I went about it. There are some limitations as you'll have to be mindful of what layers are using what tilesets and, as you guessed, sprite atlases are right out - which is annoying because they protect us against seams. However, there should be enough here to get you along your way ...

https://github.com/Seanba/ST2U_NormalMaps

![mega-lightshow](https://user-images.githubusercontent.com/6980630/67629083-1de9cb00-f83f-11e9-9b44-6eb4d8daba98.gif)
