### ISSUE TITLE
Isometric display error 

### ISSUE THREAD

**Issue by qcdong2016** [Seanba/SuperTiled2Unity#106]
import this tmx file in unity 2019
https://github.com/flareteam/flare-game/blob/master/tiled/alpha_demo/frontier_outpost.tmx

In tiled:
![089BBCFB-866D-4134-BC93-02FA828A4E6B](https://user-images.githubusercontent.com/6292878/68287136-323e8b00-00bd-11ea-83e8-e301363ca9bc.png)

In unity:
![95F15916-1093-4488-9E58-9D4B515F009A](https://user-images.githubusercontent.com/6292878/68287055-0e7b4500-00bd-11ea-81c2-4f6439f6f138.png)

**Comment by Seanba** [comment]
Hi there, @qcdong2016. This map presents a particularly tough problem because your water tiles are using a tileset offset to trick-out the system a bit and tuck water tiles under the ground tiles - but all on the same layer.

I think I may be able to add some importer options that help but you'd almost certainly be better off having your water and ground tiles on separate layers and using a `Custom Sort Axis`: https://supertiled2unity.readthedocs.io/en/latest/manual/sorting.html#dynamic-sorting-with-a-custom-sort-axis

**Comment by qcdong2016** [comment]
I follow Custom Sort Axis steps. I got this:

![Unity_2019-11-08_08-46-47](https://user-images.githubusercontent.com/6292878/68439921-5658b400-0204-11ea-9fcc-498fdef5fca5.png)

**Comment by Seanba** [comment]
Hello again, @qcdong2016. Yes, you want water and ground to be on separate tile layers so that water is explicitly underneath your ground tiles at all times. This is something you're going to need anyways as you add sprites to your game as you may want a character to be on top of one layer (like water) but underneath another layer (like a bridge in your ground layer).
