### ISSUE TITLE
Collisions Not Working

### ISSUE THREAD

**Issue by peachspit** [Seanba/SuperTiled2Unity#112]
Hello!

So I know this is a very common problem, but I've tried troubleshooting using all the methods I've read online, but still haven't had any luck with getting the colliders to work on my imported map.  It seems like the colliders themselves imported as it shows the boxes around them in Unity, but my player won't collide with them during gameplay (and I did add a 2d collision box and 2d rigid body physics to the player.)
![Screen Shot 2019-11-26 at 2 15 38 PM](https://user-images.githubusercontent.com/57774701/69664912-4986ed80-1057-11ea-9107-5824f2a30158.png)
I went through and redid all the collision rectangles using Snap to Pixel in Tiled, but that also didn't work.  I can send my Unity package if that helps.

Thanks so much!
Peachspit

**Comment by Seanba** [comment]
Hi there. Getting your collisions working correctly can be a bit of a pain at first. Do you have the project on Github? A Unity Package won't do as it doesn't include the `Tag Manager` and other project-specific settings needed to replicate.

**Comment by peachspit** [comment]
Hi Seanba! Thanks for getting back to me. I just tried adding the project to Github (I never used this platform before so I don't know if I did it right.)

**Comment by peachspit** [comment]
^ It is the "test" repository.

**Comment by Seanba** [comment]
Hi @peachspit. There's only a handful of files there. You need to add your `Assets`, `Packages`, and `ProjectSettings` directory. Thanks.

**Comment by peachspit** [comment]
@Seanba sorry, I feel like I'm doing it wrong.  It won't let me upload the entire folders, just the files individually which I feel like would only make it more confusing. Could I upload the project settings/whatever isn't in the Unity package to Github, and then email you the Unity package?

**Comment by peachspit** [comment]
Additionally, I was following this tutorial https://www.youtube.com/watch?v=nkgGyO9VG54&feature=youtu.be for lighting on my level, and the map didn't render like the sprite did after I tried to implement the 2d light rendering on the entire scene.
![Screen Shot 2019-11-26 at 5 16 57 PM](https://user-images.githubusercontent.com/57774701/69677294-92976b80-1070-11ea-8608-d4599967e724.png)

**Comment by Seanba** [comment]
@peachspit you can send me the Unity package and also a zip of your `ProjectSettings` folder.

I do recommend you become familiar with Github (or some other service) and get into the practice of backing up your project. It will make your life a lot easier. :)

**Comment by peachspit** [comment]
@Seanba Just sent to your email! Again, thank you so so much for all your help.  Newbie to all of us and seem to be having a problem at every step, of course lol.

**Comment by Seanba** [comment]
Got your project ...

Unfortunately, `RigidBody2D.Move()` doesn't work the way we'd like it to. It will move your character right through collisions. It will call `OnCollisionEntered2D` on our `gameObject` as it goes - but that's little help for us here.

What you need is something we refer to as a `Character Controller` that uses raycasts to move your character around appropriately, taking colliders into account. That can be a bit tricky to write on your own when starting out but I've had success with [Prime31's character controller](https://github.com/prime31/CharacterController2D) before when I've needed something quick. In fact, I got your collisions to work using it with just a little work.

Here's the code to your player movement class I changed a bit ...

```cs
using UnityEngine;
using Prime31;

public class PlayerMovement : MonoBehaviour
{
    public float moveSpeed = 5f;

    public Rigidbody2D rb;
    public Animator animator;

    private CharacterController2D controller;
    private Vector2 movement;

    private void Awake()
    {
        controller = GetComponent<CharacterController2D>();
    }

    void Update()
    {
        movement.x = Input.GetAxisRaw("Horizontal");
        movement.y = Input.GetAxisRaw("Vertical");

        animator.SetFloat("Horizontal", movement.x);
        animator.SetFloat("Vertical", movement.y);
        animator.SetFloat("Speed", movement.sqrMagnitude);

        // Tell the controller to move
        var translate = movement * moveSpeed * Time.fixedDeltaTime;
        controller.move(translate);
    }
}
```

... and this is your Player settings from the 01 scene ...
![image](https://user-images.githubusercontent.com/6980630/69699720-40753b00-10ae-11ea-8ad6-eded3b56ce72.png)

Note that I had to put your Player on her own layer (which I named `Player`). This is needed so that your player does not collide with herself. I also set the `Platform Mask` on the `CharacterController2D` component to be `Default` as that's the layer that SuperTiled2Unity uses by default for its colliders.

Also, note that one of your colliders (in Tiled) was still using sub-pixel coordinates ...
![image](https://user-images.githubusercontent.com/6980630/69699903-bc6f8300-10ae-11ea-9190-dbb26ecf1582.png)

... that was causing a lot of very tiny gaps in your collision geometry ...

![image](https://user-images.githubusercontent.com/6980630/69699938-d610ca80-10ae-11ea-921e-6f1350c3c164.png)

... when fixed those colliders become one smooth bar ...

![image](https://user-images.githubusercontent.com/6980630/69700099-40296f80-10af-11ea-9d9e-1624da2451e4.png)

I'll email you the Unity package with the changes I made.

**Comment by Seanba** [comment]
It sounds like you've got this working now so I'm going to close out the bug. Good luck with your game. :)
