### ISSUE TITLE
Generate Tiled maps from path

### ISSUE THREAD

**Issue by Memorix101** [Seanba/SuperTiled2Unity#118]
Is it possible to load Tiled maps from script during runtime?
I'd prepare a prefab with a custom script and pass it the string of the tmx file location to load it.

It is possible to load resources in runtime and I'd like to know how you could use it with SuperTiled2Unity. 

Example:
```cs
private string _filePath;
void Start() 
{
#if UNITY_EDITOR
        _filePath = Application.dataPath + "/config.cfg";  // loading config.cfg from within editor assets folder
#else
        _filePath = Application.dataPath + "/../config.cfg"; // loading config.cfg from binary root folder
#endif

        if (File.Exists(_filePath))
        {
            // stuff
        }
        else
        {
            // other stuff
        }
    }
}
```

![image](https://user-images.githubusercontent.com/1466920/72823780-83016100-3c74-11ea-8b24-0335f696a316.png)

Another way would be the Unity Resources folder

```cs
GameObject _prefab = Resources.Load <GameObject> ("TileBGPrefabs/" + levelNum);
```

**Comment by Seanba** [comment]
Hi there, @Memorix101. Because of the way SuperTiled2Unity depends on custom import scripts these assets must be imported at design-time (i.e. in the editor). For people wanting something close to loading at runtime then I suggest looking into Unity Asset Bundles or the newer Addressable system. Beware that these both have a significant learning code, however.
