### ISSUE TITLE
Character falling through one-way platform

### ISSUE THREAD

**Issue by sidshekar** [Seanba/SuperTiled2Unity#121]
I am not sure what is causing this problem and how you would stop it from occurring. The character is occasionally falling through the one way platform. I am using the character controller class from Prime31.

Any help would be appreciated. Thanks!

![jumpFail2](https://user-images.githubusercontent.com/2862097/72947419-cf6cae00-3de6-11ea-82d8-075537f928c9.gif)
![jumpFail](https://user-images.githubusercontent.com/2862097/72947423-d398cb80-3de6-11ea-8c80-ddae59f3feef.gif)

**Comment by AberrantWolf** [comment]
This looks to me like you're using a CharacterController-style behaviour on your swashbuckler guy. My best guess is that he's sometimes moving further than the raycasts are checking for, and so he'll be above the platform and still falling, and the next frame his bottom is already inside the platform, so the downward raycast doesn't find any edge to collide against.

The problem could be an order of operations thing (move-then-check might cause this rather than check-then-move, for instance).

Another idea might be checking the conditions which lead to the "grounded" state (when the yellow line appears).

It looks to me like the red lines are always showing where he WAS rather than where his IS, which could be a problem; so I'd start by looking for why that is.

**Comment by sidshekar** [comment]
@AberrantWolf Thanks for the response!! I was able to fix the issue!!

I actually didnt want to dive into the CharacterController2D code to fix the problem as it is someone else's code and I didn't want to mess it up. :D

I did fix the jumping on the one way platform from the ground by changing the value of  "Skin Width" in the inspector. But that would bring the ray casts closer but still fixed the problem somewhat.

For fixing while jumping on the one-way platform no matter how much I increased Skin Width it didn't fix the issue. Also the ray casts were very really close to each other. So I had to go into the code. The fix was easy. I just had to increase rayDistance by adding a constant value of 0.2f at the end of it. And that was it (I hope!!).  

There is moveHorizontal and moveVertical function. In each there is a rayDistance variable. So by resetting the value of Skin Width and by adding the 0.2f extra to rayDistance the problem is fixed.

And looking at the code it is no wonder that by increasing skin width it somewhat fixed the problem earlier as rayDistance is affected by SkinWidth.

![image](https://user-images.githubusercontent.com/2862097/72949856-5f622600-3dee-11ea-9446-9b832206e85d.png)
