### ISSUE TITLE
I cant import...

### ISSUE THREAD

**Issue by Dortys** [Seanba/SuperTiled2Unity#145]
SuperTiled2Unity version: 1.9.1, Unity version: 2019.4.3f1
Could not find tile 221230376. Make sure the tilesets were successfully imported.
Could not find tile 218300512. Make sure the tilesets were successfully imported.
Could not find tile 8388609. Make sure the tilesets were successfully imported.
Could not find tile 19968. Make sure the tilesets were successfully imported.
Could not find tile 256460800. Make sure the tilesets were successfully imported.
Could not find tile 5261312. Make sure the tilesets were successfully imported.
Could not find tile 206635008. Make sure the tilesets were successfully imported.
Could not find tile 193142816. Make sure the tilesets were successfully imported.
Could not find tile 139728186. Make sure the tilesets were successfully imported.
Could not find tile 34472624. Make sure the tilesets were successfully imported.

I went in to the .tmx file and there was nothing that statet a problem there. I have literally no idea what to do

**Comment by ijacquez** [comment]
I just tested a few, but none of them have the flags set on the tiles.

You need to provide more information. How many tilesets you have, how many tiles in those tilesets, etc.

Have you been able to find roughly where the problem is? That is, find the layer that's causing the issue, then attempt to find roughly where the problem is.

**Comment by StudTheSystem** [comment]
right? I have checked the dependencies to make sure all the files were in the right locations and the missing error message is gone, now the only problem I'm be given is from the tmx file, which is pretty much what you posted.

**Comment by Seanba** [comment]
Hi there, @Dortys. Sorry about the error but Tiled was upgraded with a new compression format that is not available to Unity (and therefore SuperTiled2Unity).

The fix is to select a different `Tile Layer Format` for your map in Tiled.

![image](https://user-images.githubusercontent.com/6980630/88471871-7f74be00-ced3-11ea-90bf-044b023611e2.png)

The latest version of SuperTiled2Unity will give you and others a better error message to act on.

![image](https://user-images.githubusercontent.com/6980630/88471878-93202480-ced3-11ea-8036-a5986c699e08.png)
