### ISSUE TITLE
Deleting a tile at runtime collision remains

### ISSUE THREAD

**Issue by phantasie** [Seanba/SuperTiled2Unity#153]
Hi

First: Amazing tool you've provided Seanba. As a fellow game dev, I'm impressed :)

Issue: Setting a tile to null leaves behind the collision information.

Specifics:

I'm deleting a tile at runtime when I collide with it, ie

`private void OnTriggerEnter2D(Collider2D collision)    {`
  `  var tm = collision.transform.parent.gameObject.GetComponent<Tilemap>();`
  `  var closestPoint = collision.ClosestPoint(transform.position);            `
  `  Vector3Int cellPosition = tm.WorldToCell(closestPoint);`
  `  tm.SetTile(cellPosition, null); `

The tile itself dissapears but the collision is left behind.
I still collide with it when doing the Raycast

`var hit = Physics2D.Raycast(pos, m_Facing, MovementBlockSize, 1 << LayerMask.NameToLayer("Resource"));`

**Is this the proper way to remove a tile + its collision at runtime, or am I missing something simple.**

Notes:
- Unity 2019.2.2f1
- Default settings
- 16 pixel units
- Setup collision in Unity using collision editor

**Comment by Seanba** [comment]
Hi there, @phantasie. The issue here is that SuperTiled2Unity, by default, gathers all collision geometry in a Tiled Layer and combines them into one large `PolygonCollider2D` object. This is why the collision remains, so to speak, even though you removed the tile from the scene.

For tiles that you want to treat as dynamic objects I suggest you use use Tile Objects (in an Object Layer in Tiled). These Tile Objects are imported as separate `GameObjects`s with their own collision so when you remove them from the scene you will remove the colliders on it as well.

A quick way to turn all your tiles into Tile Objects is to use the `Tiles as Objects` in the inspector for your TMX map file in Unity.

![image](https://user-images.githubusercontent.com/6980630/91003104-0336ce80-e596-11ea-8fe2-f917a33ce4a3.png)

I recommend this just for testing, however, as it will turn every single tile on every single Tile Layer into a separate `GameObject` in Unity. In practice you will want to be more selective of which tiles are treated as objects.

Hope that helps.

**Comment by phantasie** [comment]
Hi Seanba

This makes perfect sense. Thanks for following up. Ill close this comment as its not a bug.
