### ISSUE TITLE
Importing Issue

### ISSUE THREAD

**Issue by MConnolly15** [Seanba/SuperTiled2Unity#154]
Hi,

i am using supertiled2unity to move a level from tiled to unity. However, i am having issues when i import it. I'm not sure what it's asking me to do, they're all in the same folder, all have the same location etc and keeps throwing me errors. I have been trying to get this to work for about 3 days straight and really starting to drive me crazy so help would be greatly appreciated!!

https://streamable.com/hsilqg

**Comment by MConnolly15** [comment]
I was able to get a way around it by embedding the tsx file in tiled. However, its screaming at me that it doesn't like it and i have invalid rectangle issues which i have no idea how to fix? https://imgur.com/a/LDGdsrk

**Comment by Seanba** [comment]
> they're all in the same folder

That's probably the problem. Were all your TMX, TSX, and texture files in the same directory when originally creating your maps in Tiled? The relative paths between these files must be preserved when importing into Unity.

>  However, its screaming at me that it doesn't like it

Hey, I understand the frustration that comes with game development (believe me!) but I promise you I did not make this tool to scream at you. And even if I did, wouldn't you want to know when something is not set up correctly?

**In this case:** That's a warning that embedded tilesets are not shared across different maps. This will bloat the memory used by your game as every map that uses those tilesets will have to recreate and manage each tileset itself.

>and i have invalid rectangle issues

That's probably because you placed rectangles on tiles in the Tiled Collision Editor without sizing them. In that case the rectangles have a zero width and height. Check out your tiles in the Collision Editor (in Tiled) and look at these properties for your rectangle and give them an explicit width and height. You can do that be entering values "by hand" or dragging the corners of the rectangle around in the collision editor.

![image](https://user-images.githubusercontent.com/6980630/92334441-89055000-f053-11ea-9bd3-fb792382f068.png)

It may be difficult to find exactly which tiles have these degenerate rectangles in them but you can use the `ID` to help you narrow it down. It looks like you have at least 919 tiles in that tileset which is a lot of tiles to manage in one tileset, IMHO.

**Comment by MConnolly15** [comment]
I think i found a way around doing it without the embedded tileset etc however.. https://streamable.com/gby0ua  Just this one issue i have! When import this png file (tileset) unity is changing the path? https://streamable.com/gby0ua

Thanks for the answer on the other stuff, i certainly will address those issues once i get around the above first.

**Comment by Seanba** [comment]
It's not the path is changing, per se. You imported the texture into Unity at that location but your tileset is still referencing the texture in it's original location, outside of your Unity project.

**Try this:** Double click on your `town.tmx` file in Unity. That should open Tiled with a warning that your tileset or texture files could not be found. Then, in Tiled, search for those missing files using the files that you have imported into Unity.

**Comment by Seanba** [comment]
Actually, you won't get any errors in Tiled if those files outside of Unity still exist in the original location. Send me your TMX and TSX file and I'll show you how to fix it by hand.

**Comment by Seanba** [comment]
Somehow your `tw.tsx` file got renamed to `tw.xml`. Changing that file back to having the tsx extension fixed it for me.

**Comment by MConnolly15** [comment]
When i change to tsx it doesn't make a difference for me. Still throws error. I have no doubt i am doing the whole process wrong so that is why i have recorded what i do, i have tried other methods to! I hope this video helps to identify what i am doing wrong, thanks!

https://streamable.com/ltl80z

**Comment by Seanba** [comment]
It looks like you only imported the map file and then when you went to "locate files" in Tiled you "located" the files on your desktop. You need to have all files imported to Unity and if you have any issues with paths then you have to "locate" the referenced files that are themselves in Unity. Does that make sense?

**Comment by MConnolly15** [comment]
When i import them all and then go into tiled i don't get that same error message though, i don't get any error messages at all? 

https://streamable.com/lw9vo7

**Comment by Seanba** [comment]
Please send me your Unity project. It will be easier for me to fix and explain what I did after I'm confident it's working.

**Comment by MConnolly15** [comment]
[gameProject2020.zip](https://github.com/Seanba/SuperTiled2Unity/files/5180521/gameProject2020.zip)

Sorry for being such a nuisance man and thank you for being a legend like this and helping me.

**Comment by Seanba** [comment]
I took the files you sent me and even though there are errors due to zero-width colliders I was still able to drag the `town` prefab into my scene hierarchy and it worked ...

![image](https://user-images.githubusercontent.com/6980630/92338741-f62adc80-f077-11ea-83b3-1865c0e52e2b.png)

**Comment by Seanba** [comment]
To fix those errors ...

Remove the zero-width rectangles from your tiles ...
![image](https://user-images.githubusercontent.com/6980630/92338775-2d998900-f078-11ea-8fed-ac98584928d5.png)

![image](https://user-images.githubusercontent.com/6980630/92338780-38541e00-f078-11ea-8423-8d73387dc790.png)

![image](https://user-images.githubusercontent.com/6980630/92338795-41dd8600-f078-11ea-99a1-ee7a57a9e784.png)

**Comment by Seanba** [comment]
BTW, a couple of pointers not really related to your issues here:

- You are importing files into the SuperTiled2Unity folder. You should import your files into your own folder. I may change the SuperTiled2Unity contents around on you without you being aware of it if you upgrade to a later version of SuperTiled2Unity.
- I noticed you are using an alpha build of Unity. Unless there is something specific about that version that you know you absolutely need then I would keep with stable versions of Unity.

**Comment by MConnolly15** [comment]
![image](https://user-images.githubusercontent.com/58251832/92339170-b5998600-f0ac-11ea-873f-96975395aeac.png)
I get this when i drag it across. Just a circle?

**Comment by Seanba** [comment]
I think you need to fix the tiles that are being reported again. Tileds 757, 786, and 919 have rectangles on them that have zero width.

**Comment by Seanba** [comment]
Here's how I fixed those errors in case you're having problems figuring it out. If you are downloading tilesets from other people then you should be prepared that you'll need to do this ...

Here are the errors reported ...
```
SuperTiled2Unity version: 1.9.3, Unity version: 2019.2.10f1
Invalid rectangle (Tile ID ='757') in tileset 'tw' has zero width
Invalid rectangle (Tile ID ='786') in tileset 'tw' has zero width
Invalid rectangle (Tile ID ='919') in tileset 'tw' has zero width
```

First, I open your map in Tiled and click on the Edit Tileset button ...
![image](https://user-images.githubusercontent.com/6980630/92339629-c16d5400-f07c-11ea-9283-8ab482ea6034.png)

Then find your tile by Tile ID. I'm going to find Tile 757 for instance.

![image](https://user-images.githubusercontent.com/6980630/92339722-288b0880-f07d-11ea-85db-1fcceb70237e.png)

These IDs are sequential so it's easy to track down.

Then lasso over everything on the Tile to find the degenerate rectangle ...

![image](https://user-images.githubusercontent.com/6980630/92339794-5ff9b500-f07d-11ea-89a4-54b9c6a992d6.png)

See how that selected rectangle has no width? Either delete that or give it a proper width. Do that for your other tiles being reported and you should be in working order.

**Comment by MConnolly15** [comment]
Okay done that and imported it into Unity.  but now it's asking for tile.png which i have imported as you can see above it. 
![image](https://user-images.githubusercontent.com/58251832/92340091-f98e8a00-f0b0-11ea-8092-5f12cd7fef75.png) 

and town still  says: 
![image](https://user-images.githubusercontent.com/58251832/92340115-0f03b400-f0b1-11ea-84c6-93690e405b9b.png)

and when i double click on town, i dont get any errors to ask me to locate anything

**Comment by Seanba** [comment]
Unfortunately we are ping ponging between two different types of errors here and it looks like you re-imported a tileset file that is referencing a texture outside of Unity when you would have been better served fixing the rectangles in the tileset _inside_  your Unity project that already had that _other_ issue fixed. Know what I mean?

`../../../../Desktop/Files/tile.png` is a file outside your Unity project. You need your tileset to use the texture you imported into Unity instead. The quicker you get away from downloading files and moving them around the better.

Anyhow, the fix is still easy. Open your Unity version of the `tw.tsx` file in a text editor and look at the `image` element (probably on line 3). You want it to be like this ...

```
<image source="tile.png" trans="ff00ff" width="576" height="496"/>
```

That `source` attribute will use the `tile.png` that is in the same folder as your TSX file, in Unity, instead of whatever ungodly path it has into your desktop.

The reason why you don't get this error in Tiled is because Tiled knows how to reference and load files anywhere on your harddrive. Unity can only reference and load files that have been imported into your Unity project.

**Comment by Seanba** [comment]
Here's the points that are essential to understand:

1. All your files (maps, tilesets, and textures) must be imported into Unity.
2. The relative paths between these files must be kept intact inside Unity. Look at your TMX and TSX files in a text editor to see how these files reference each other.
3. Having files across different folders on your harddrive (a download directory, your desktop, whatever) is going to make this more difficult.

**Comment by MConnolly15** [comment]
![image](https://user-images.githubusercontent.com/58251832/92341660-4de83880-f0b6-11ea-8bb7-d033e618f5ab.png)
 
You can see the path at the top and it also has the tile.png when i open in text editor. 

and the TMX file references the tw.tsx file?

![image](https://user-images.githubusercontent.com/58251832/92341785-a4557700-f0b6-11ea-932f-c4e5f7307dde.png)

**Comment by Seanba** [comment]
Try forcing your TMX to be re-imported. In may be that you were importing your files one-at-a-time (you can select multiple files at once) and the dependencies between files were just not established. In other words, `town.tmx` did not know to automatically re-import itself when `tw.tsx` was updated.

![image](https://user-images.githubusercontent.com/6980630/92345523-3f3a5b00-f08f-11ea-8e1b-b5e962439396.png)

Once this is working and the dependencies are established then any future changes you make to your tileset or texture file with trigger your map file to be updated in Unity.

**Comment by MConnolly15** [comment]
Finally got around it. Opened town from unity. Navigated to tw.tsx and went to the image property, edit and changed it from the one i had on my desktop to the one i had imported on unity and it worked! 

Thanks so much man your patience here has been incredible. I wish i could buy you a pint.

Thanks a lot!!

**Comment by Seanba** [comment]
Sorry for the late replay, @MConnolly15, but I'm glad you got it sorted out. Good luck with your game. :)
