### ISSUE TITLE
Can't import the tiled map

### ISSUE THREAD

**Issue by FahrulID** [Seanba/SuperTiled2Unity#165]
The TSX file show this error :
SuperTiled2Unity version: 1.10.0, Unity version: 2019.3.9f1
Texture was imported at a smaller size. Make sure 'Max Size' on 'pokemon_tileset_from_public_tiles_by_chaoticcherrycake_d5xdb0y.png' is at least '2400'

and the TMX file show this error : 
SuperTiled2Unity version: 1.10.0, Unity version: 2019.3.9f1
Errors detected in tileset 'pokemon_tileset_from_public_tiles_by_chaoticcherrycake_d5xdb0y.tsx'. Check the tileset inspector for more details. Your map may be broken until these are fixed.
Could not find tile 2102. Make sure the tilesets were successfully imported.
Could not find tile 2103. Make sure the tilesets were successfully imported.
Could not find tile 2104. Make sure the tilesets were successfully imported.
Could not find tile 2242. Make sure the tilesets were successfully imported.
Could not find tile 2382. Make sure the tilesets were successfully imported.
Could not find tile 2383. Make sure the tilesets were successfully imported.
Could not find tile 2384. Make sure the tilesets were successfully imported.
Could not find tile 2243. Make sure the tilesets were successfully imported.
Could not find tile 2244. Make sure the tilesets were successfully imported.

What I did wrong ?

**Comment by Seanba** [comment]
Hi there, @FahrulID. Take a look at the texture importer settings for your `pokemon_tileset_from_public_tiles_by_chaoticcherrycake_d5xdb0y.png` texture. If you view it in the inspector I would guess that you have it set to be imported so that the `Max Size` is `2048` or some other number that is less than 2400. This is a common issue when using large tileset images.

Try bumping that number up to `4096` and then press `Apply` to reimport the texture. That should automatically reimport the TSX and TMX files that use that image and will fix them up.

![image](https://user-images.githubusercontent.com/6980630/105127303-3a0e0380-5aa6-11eb-8e2f-16ba6e6e9beb.png)

**Comment by FahrulID** [comment]
> Hi there, @FahrulID. Take a look at the texture importer settings for your `pokemon_tileset_from_public_tiles_by_chaoticcherrycake_d5xdb0y.png` texture. If you view it in the inspector I would guess that you have it set to be imported so that the `Max Size` is `2048` or some other number that is less than 2400. This is a common issue when using large tileset images.
> 
> Try bumping that number up to `4096` and then press `Apply` to reimport the texture. That should automatically reimport the TSX and TMX files that use that image and will fix them up.
> 
> ![image](https://user-images.githubusercontent.com/6980630/105127303-3a0e0380-5aa6-11eb-8e2f-16ba6e6e9beb.png)

Thanks for your reply, that's the issue. Even though I already fixed it before.
