### ISSUE TITLE
Collider not working properly

### ISSUE THREAD

**Issue by FahrulID** [Seanba/SuperTiled2Unity#168]
So I made a collider in tiled that is 1 tile big

And when I import the map and play with my character which has a box collider ( tested with a 

range of 0.9x0.9 to 1x1 tile ) still not working properly sometimes

**Comment by FahrulID** [comment]
By not working properly i mean it stuck sometime and can't move to the desired position

**Comment by Seanba** [comment]
Hi there, @FahrulID. Characters getting stuck in geometry is a common issue in game development and it will come down to the specifics of your game. I suggest you try to get this working first with characters and collisions that are not generated by SuperTiled2Unity (i.e just using simple 2D boxes). That way you will have better luck getting assistance on the Unity forums if you need extra help.

Once you have your character collisions working to taste then you can try it against colliders made by SuperTiled2Unity. If this turns out to be a problem specific to ST2U then we can take a deeper look.
