### ISSUE TITLE
Can't get my map to load

### ISSUE THREAD

**Issue by cribblesnbits** [Seanba/SuperTiled2Unity#185]
I am new to the game creation field, and I am just trying to get the hang of unity, tiled, and supertiled2unity.  I created a test level with a basic tileset and made sure that the image, tsx, and tmx were all saved in a folder within the supertiled2unity folder inside of a created folder called imports.  I tried to drag and drop the tiled level into the project and all I get is an invisible object. 
![temp pic](https://user-images.githubusercontent.com/86176823/122661386-b3924680-d157-11eb-9cf4-8da1ca516cac.png)

I got to this point by watching someone's youtube video, and for what I can tell, I have things in order.  I am not sure if there are any behind the scenes settings that I need to do.  Any help would be appreciated.

**Comment by Seanba** [comment]
Hi there, @cribblesnbits. Are all the files supposed to be in the same folder? My bet is that your source TMX, TSX, texture files are in different directories (before you copy them over to Unity) so you are losing the relative paths between them when you put them all in the same folder (in Unity), If you look at your TMX file in Unity's Inspector UI there should be an error message telling you this is the case. Additionally, if you tried to open your Unity's version of your TMX in Tiled then I'd expect Tiled to complain too about not being able to find files (again, because the relative path to files has been broken).

I've tried to make ST2U easy to use but there are two cardinal rules to having your Tiled files imported into Unity:

1. All dependencies must be imported into your Unity project (for instance, a TSX has a dependency on texture files. Those texture files have to be in Unity in order for a TSX to be imported)
2. The relative path between your TMX, TSX, and texture files must be kept intact.

For example, if your folder structure looks like this before you copy all your files in Unity:

```
.../MyTiledFiles/MyMap.tmx
.../MyTiledFiles/Tilesets/MyTileset.tsx
.../MyTiledFiles/Textures/MyTexture.png
```

Then you want to copy over the `MyTiledFiles` folder into your Unity project. This will import all the files in the sub-directories  too. Some people have their TSX and texture files all over the place on their computer which may make this kind of thing a challenge. You'll want to group your files and then import them all in one go. Think of how you would gather your Tiled files into a zip to share with someone and you may get the idea.

**Comment by cribblesnbits** [comment]
Thank you!  I can see it now.  I appreciate your prompt and detailed response.  Even though I am just beginning, I am having a bunch of fun learning this.
