### ISSUE TITLE
Couldn't find tile number 

### ISSUE THREAD

**Issue by Promax1113** [Seanba/SuperTiled2Unity#188]
SuperTiled2Unity version: 1.10.2, Unity version: 2020.3.15f2
Errors detected in tileset '../Assets/roguelikeSheet_transparent.tsx'. Check the tileset inspector for more details. Your map may be broken until these are fixed.
Could not find tile 6. Make sure the tilesets were successfully imported.
Could not find tile 63. Make sure the tilesets were successfully imported.
Could not find tile 3. Make sure the tilesets were successfully imported.
Could not find tile 4. Make sure the tilesets were successfully imported.
Could not find tile 5. Make sure the tilesets were successfully imported.
Could not find tile 60. Make sure the tilesets were successfully imported.
Could not find tile 61. Make sure the tilesets were successfully imported.
Could not find tile 62. Make sure the tilesets were successfully imported.
Could not find tile 117. Make sure the tilesets were successfully imported.
 
Says this, I've tried everything. I can't get it to work.
![image_2021-08-08_190720](https://user-images.githubusercontent.com/67706765/128639795-0edbf4f9-eff0-4cc2-b7fc-7985bd119f21.png)
Theese are the assets for the map.

**Comment by Seanba** [comment]
Hi there, @Promax1113. Those errors are reported from the inspector when a TMX is selected. It is telling you that something is wrong with a TSX that it depends on. Clicking on that TSX in the inspector you should be able to see what the real problem is. My guess is that the TSX file is expecting the texture to be in a different folder. Were all your assets (TMX, TSX, and texture) all in the same directory _before_ you imported them to Unity?

**Comment by Promax1113** [comment]
Hi, @Seanba. I had the images in one folder on my hard drive and the TSX and TMX saved directly into unity.

**Comment by Promax1113** [comment]
Hi again @Seanba. I put all the assets in a folder, then imported them to unity and it ``worked``.

Thanks for the help!
