### ISSUE TITLE
performance boost when importing tmx files

### ISSUE THREAD

**Issue by cjz9032** [Seanba/SuperTiled2Unity#189]
Hello 
![image](https://user-images.githubusercontent.com/11435814/128659485-b879b569-ac98-4d33-829b-1b6e83c03649.png)
As you can see the above image, it tokes so long time(  about 500 maps, and their average size is 100x100 ), but my maps and tilesets are so simple that even without any custom-property,
**Map**
![image](https://user-images.githubusercontent.com/11435814/128659875-a1ab5157-0ef1-4c86-a9aa-52a6a2fafa41.png)

**Tile Sets**
![image](https://user-images.githubusercontent.com/11435814/128659865-9ab6ce81-e015-47b2-8362-63ec6420f860.png)

I'm struggling to improve performance about importing maps, someone can help me?

Thanks

**Comment by Seanba** [comment]
Hi there, @cjz9032. Usually when we run into slow import times it's because of highly complex collision volumes but in your example tileset there is no collision geometry. Is that common for your project?

If import performance is uniformly bad (around 15 seconds a map, I'm guessing) then it would be good to profile importing only one map to see where the time it spent. Unity has a built in profiler that is super useful for such things.

Is it possible for you to send your project to me? I may not be able to get to looking into it for a couple of days but I'm curious about those import times.

**Comment by cjz9032** [comment]
> Hi there, @cjz9032. Usually when we run into slow import times it's because of highly complex collision volumes but in your example tileset there is no collision geometry. Is that common for your project?
> 
> If import performance is uniformly bad (around 15 seconds a map, I'm guessing) then it would be good to profile importing only one map to see where the time it spent. Unity has a built in profiler that is super useful for such things.
> 
> Is it possible for you to send your project to me? I may not be able to get to looking into it for a couple of days but I'm curious about those import times.

sorry for later reply @Seanba 
at yesterday i found the reason, just cause of unity is in debug mode....so stupid am I.
so, finally when I change to release mode, only spend 30mins to process these 500 maps

**Comment by cjz9032** [comment]
![image](https://user-images.githubusercontent.com/11435814/129687159-956edcfe-a40d-4e3d-9aac-4abac9d070d1.png)

BTW,  I found the profile, but i can't understand what happened

**Comment by Seanba** [comment]
Hi there, @cjz9032. Sorry for the late reply. `GetTileAnimationData` is invoked by the Unity Editor itself so I'm afraid I don't have much control over that. If you are still experiencing extra long import times for small maps let me know and I'll take a look. Thanks.
