### ISSUE TITLE
Really huge project size after importation

### ISSUE THREAD

**Issue by Natlink** [Seanba/SuperTiled2Unity#21]
Hello,
I have noticed an issue with the size of my project.
I have an average of 500 tiles sized 64*64, and an huge number of maps ( more than 300 at the end )
I test to import only a little set of map ( 12, who used lot parts of tilesets ), but after than your script import map in unity, my project folder size is over 2go ( less than 400mb before ), so i'm a bit affraid of the size if i import all of my map.
After building project, the build size stay really high.
The huge size seems to come from Library/ metadata and some files.
So, did the script when importing a map create a new map with all tiles, or only get the reference froms tilesets ?
I stay here if you need more informations.
Thanks

**Comment by Seanba** [comment]
Hi thee, Natlink. Are you using tilesets (TSX files) that are shared between your maps? I wonder if your project is using too many texture atlases for embedded tilesets (tiles that are defined within the TMX instead of external in TSX).

If you turn off Texture Atlasing for your maps and tilesets does the size go down considerably? I'm not saying that's the solution here but it may help us track down what is going on.

**Comment by Natlink** [comment]
Re,
After some test, it seams to be that!
I change on a set of map the tileset sprite reference to tileset tmx file, and the size reduce lot!

So in result, they are always a "big" size, but it's static and don't really grow when map number grow it's just the static cost of the tileset i mind.

Thanks for your advice, and sorry for the issues, of course it appears to not be an issues, juste an error from me ...
 ( Thanks for your excellent project ;) )
