### ISSUE TITLE
Imported TileMap is in the wrong place

### ISSUE THREAD

**Issue by Leonniar** [Seanba/SuperTiled2Unity#220]
I just imported my tilemap and it appears in the wrong place as you can see here: [https://prnt.sc/k8OZ7iMDAlXn](url)
I have no idea why this is happening, It's really frustrating since I am working on a game jam and I have found 0 help regarding this :) 
Unity ver:  2021.3.0f1
Tiled ver: 1.9.0
SuperTiled2Unity ver: 1.10.5

**Comment by seanb-22ct** [comment]
Hi there, @Leonniar. If you send me your Tiled files I can try to take a quick look.
A common issue is to make sure your TMX (map) and TSX (tileset) files are using the same `Pixels Per Unit` value.

**Comment by seanb-22ct** [comment]
email sean@seanba.com

**Comment by Seanba** [comment]
Hi again, @Leonniar. Thanks for the files. I'll continue to talk through this issue here in case others find it useful.

The `Pixels Per Unit` is a Unity conceit they use for sprites and is a import option for textures. By default, 100 pixels equals one numeric unit along the x and y axis.

The import settings for Tiled maps and tilesets have this same setting and it's important to keep them the same.

![image](https://user-images.githubusercontent.com/6980630/179371826-a0ee80be-4641-4dc5-b599-13a329dc54ca.png)

However, that is not the problem here. It appears to me you have two issues:
1. You map position is far to the bottom (and a bit to the right) of the origin
2. Your tiles are overlapping each other incorrectly

For your first issue this seems like the map is being positioned exactly how you have it in Tiled. If you turn on the grid in Tiled you should see how your map is positioned ...

![image](https://user-images.githubusercontent.com/6980630/179371912-58cc78e5-3374-4df8-b3cc-c5bb3463c038.png)

For the second issue this how your isometric tiles are rendered over each other wrong ...

![image](https://user-images.githubusercontent.com/6980630/179371967-33a0fab6-6ace-4b63-b948-7bc9ce941905.png)

Isometric maps are historically difficult to get just right but if you use a custom sort axis that should help. Select your Tiled map in the inspector and set `Layer/Object Sorting` to `Custom Sort Axis`

![image](https://user-images.githubusercontent.com/6980630/179372017-15f378c1-3f74-44f0-ba06-acfc1fabed53.png)

Note that I have the sort axis set up in my project `Graphics` settings so that tiles with a higher Y value are drawn first.

![image](https://user-images.githubusercontent.com/6980630/179372119-a7b83dca-24e7-4ceb-896e-b5d3192cc520.png)

Hope that helps. Good luck with your jam.

**Comment by Leonniar** [comment]
Thanks, I figured out the grid thing as soon as I sent it out, silly mistake hahaha. So If I started the map at the top it would appear correctly right ? I figured out the rendering order as well, didn't know it was like that in the screenshot but still usefull for anyone that might get this problem.

Thanks a lot for all the help !
