### ISSUE TITLE
Chunk tiles sorting differently based on position within map

### ISSUE THREAD

**Issue by MabLuxx** [Seanba/SuperTiled2Unity#222]
I have an issue where the sorting behavior of tiles appears to change unpredictably when placed on a layer utilizing Chunk sorting mode.

In the pictures below, the tiles all exist on the same layer in tiled. The grouping with the rock peaking out has been copy/pasted down to the bottom left to demonstrate the different results once imported into Unity. The first image is a screenshot from Tiled, this displays the proper sorting of all tiles.
![ST2U Tiled Result](https://user-images.githubusercontent.com/43322300/185232082-24d4aa2b-456b-4f81-b611-a4a785290107.png)

The second image here is a screenshot of the tilemap imported into Unity. As you can see the sorting between the copy/pasted grouping of tiles is different than that of the original grouping.
![ST2U Unity Result](https://user-images.githubusercontent.com/43322300/185232089-9193a43c-ad61-469f-95b2-7b7b1a9abce6.png)

My initial guess is something related to the grouping of tiles, but I have no real idea of where to begin looking.

Here are my map properties
![image](https://user-images.githubusercontent.com/43322300/185233410-d9959a33-98f3-4d84-bea6-bcde7011422b.png)

And the TMX properties taken from the file in Unity
![image](https://user-images.githubusercontent.com/43322300/185233624-cf76773f-83ba-4016-995b-f644919dbfa2.png)
![image](https://user-images.githubusercontent.com/43322300/185233684-59b06ee5-8a37-407a-a4dd-2b8398753558.png)

Thanks in advance!

**Comment by Seanba** [comment]
Hi there, @MabLuxx. I won't be near my work PC for a couple of days but in the meantime this link might shed some light:

https://github.com/Seanba/SuperTiled2Unity/wiki/Sorting-with-SuperTile2Unity

If that doesn't help then can you send me your Tiled files? Or maybe your whole Unity project if it's easy enough to share? My email is sean@seanba.com. Thanks.

**Comment by Seanba** [comment]
Thanks for sending me your files, @MabLuxx. I see what you're talking about now.

I had to go back over my notes to figure out what's going on but, quite simply, the `Chunk` setting for `Tilemap Renderer Mode` doesn't work well with "complicated" sorting because of the way Unity batches tiles together.

By "complicated" sorting I mean maps with tiles that overlap each other. Isometric maps, in particular, have this challenge. Your map is orthogonal but because you have large tiles (like `64x64` in size) on a small grid (`4x4`) you have to use the `Individual` mode setting in order to properly sort your tiles.

Importing your map using the `Custom Sort Axis` setting for `Layer/Object Sorting` should fix you up. This makes your layers use the `Individual` mode.

![image](https://user-images.githubusercontent.com/6980630/185756606-2c7bdd61-174c-473c-a3f8-9c30b635049a.png)

Hope that helps.

**Comment by MabLuxx** [comment]
Hi Sean,

Thanks for getting back to me so soon. I saw your previous email, and that
is actually the wrong map. The most easily recognizable case displaying the
issue is found on the map named *Tiling Chunk Sorting Issue.tmx*

Once imported into Unity, the issue is apparent when comparing the two
groupings of rocks/trees. The cluster near the red 'x' sorts incorrectly,
where the one on the bottom left by the green checkmark appears correct
(this image is from tiled and shows both clusters correctly).

[image: image.png]

However, I do believe you have identified the root cause of this. I had
thought it possible that my irregularly large tiles mixed with the small
4x4's on a chunk layer could be the cause for my issue. The batch sizing in
Unity was my initial thought, and I have not yet attempted to dig into
modifying/configuring this, or if I should even attempt to.

Due to an approaching deadline, I have currently settled on modifying the
detail on the map in the affected areas. Setting the layer to individual
and forcing a large amount of 4x4 tiles to sort individually deals a bit of
a blow to the game's performance (at least in editor) that I would rather
avoid.

I appreciate you taking time to look at this for me. I have been happily
utilizing Tiled/ST2U and Aseprite2Unity for years now, and have nothing but
gratitude for the work you have done to evolve and support these tools.

Thanks again!
Max
