### ISSUE TITLE
Trying to change tile sprites at runtime, can't alter tsx textures

### ISSUE THREAD

**Issue by roomyrooms** [Seanba/SuperTiled2Unity#229]
Hey!

I'm currently trying to create a system for swapping between tilesets based on in-game seasons. The premise is pretty simple: create two tilesets for two seasons, place sprites in the tileset at the same place (e.g. a snowy tree in winter and a normal tree in summer), then swap out the tsx textures at runtime when necessary.

This is proving to be pretty difficult in ST2U though and I was hoping I could get some guidance on how to achieve this effect given it seems I'm either unsure or incapable of directly changing the textures themselves.

Any help would be greatly appreciated!

**Comment by Seanba** [comment]
Hi there, @roomyrooms. Back in the old days swapping out a spritesheet would be an easy way to give the layers of your map a different look provided that all your sprites/tiles/cells were in the same location on each separate sheet.

Unity (and other modern engines) make it a bit harder because the source textures are often copied around into larger textures in order to reduce draw calls.

But with a little bit of work you can pull of what you want. I provided a Github example where I use a custom material to swap out summer and winter "tilesets" in realtime. The readme should help lead the way but let me know if you have any questions.

https://github.com/Seanba/ST2U_SwapTexture

**Comment by roomyrooms** [comment]
Apologies for the delay- this is perfect! Works great, thanks for the help.
