### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by inspirsea** [Seanba/SuperTiled2Unity#235]
Hi, great plugin. Have used it for a while now and it works really well its exactly what I need for easy integration to unity.

However when we make changes in tiled it takes an awful long time to reimport the changes. This is have started to become an issue when our maps have gotten more numerous a swell as more complex.

I believe the main problem is the polygon collider, but could be mistaken.
I set up a minimalistic unity project exemplifying the issue.

https://github.com/inspirsea/SuperTiledPerformanceTest

This project takes around 10min to reimport the map if I make a change in tiled. This seems a bit excessive as the map is quite small and doesn't use a lot of different tiles. I would be grateful if you could take a look at the issue. Either if there is some optimization issue, bug or incorrect setup on my side.

**Comment by seanb-22ct** [comment]
Hi there, @inspirsea. Thanks for putting together a test project on Github for me to play with.

I'll take a look at this later on today but head's up that the problem _might_ be that you are using a sub-pixel points in the collision editor for your tiles. That causes a lot of slivers and degenerate polygons. It's hard for any algorithm to merge that can kind of geometry, at least quickly.

FWIW, ST2U uses [Clipper](http://www.angusj.com/clipper2/Docs/Overview.htm) for combining colliders. It's a great piece of software that is battle-tested and widely-used but there's only so much it can do.

But I'll take a closer look at your project later to confirm that is your issue. In the meantime you may want to turn on `Snap to Pixels` in Tiled.

![image](https://user-images.githubusercontent.com/18538373/217372321-bb419fcb-795c-4d47-ae7f-8e4d7b741888.png)

**Comment by seanb-22ct** [comment]
Okay, there are some issues with your tile collider geometry afterall which is going to greatly effect performance of the importer.

I'm going to post these as I find them.

The biggest contribution to the slow import times is your tiles that have both ice and water regions ...

![image](https://user-images.githubusercontent.com/18538373/217399888-5cc850d1-d288-4053-94de-9bf3bf42cfe1.png)

You want those collisions to have nice and even points on pixel boundaries (not bleeding outside the tile if possible).

![image](https://user-images.githubusercontent.com/18538373/217400026-4ba278ec-924b-4143-8808-044ada8e85d2.png)

Further, you want to put those colliders on separate physical layers. That part is essential otherwise you end up crazy collision shapes that are expensive to compute.

![image](https://user-images.githubusercontent.com/18538373/217400282-dbd02064-2018-417e-9fac-f78c433c1037.png)

![image](https://user-images.githubusercontent.com/18538373/217400558-e929c6ed-af43-4b11-a0ed-0818a26f39d9.png)

![image](https://user-images.githubusercontent.com/18538373/217400573-8f4e0476-e962-455d-b460-427d0b9decaf.png)

**Comment by seanb-22ct** [comment]
A lot of your tiles have sub-pixel X,Y values, have sub-pixel points/nodes on their polygons, have extra points they don't need, they bleed outside the tile, and they are all grouped into the `Default` collision layer (because they are not using `unity:layer`).

Like this ...

![image](https://user-images.githubusercontent.com/18538373/217402139-0cf317f7-088e-49e5-a6e0-e3ccf4c8c0cd.png)

But this is better ...

![image](https://user-images.githubusercontent.com/18538373/217402150-c5e85544-2943-430e-adbc-061285298acc.png)

(Pixel snapping in Tiled will fix up having sub-pixel coordinates)

**Comment by seanb-22ct** [comment]
Here's an example where you should use rectangles instead of polygons. Place them with pixel snapping and put the them in different water and ice Unity layers.

![image](https://user-images.githubusercontent.com/18538373/217403213-bb33434a-4cd2-492e-9d09-1aebb9e26fb0.png)

**Comment by seanb-22ct** [comment]
I went through some of tiles and cleaning up their collisions made the (re)import go from 10 minutes down to 30 seconds.

That's still too long IMHO but if you follow suit with the other colliders in the Tile Collision Editor (in Tiled) then you should be in good shape.

I've attached my changes to your `Winter.tsx` file (with a txt extension so I can post). Note that you will need to add the `Ice` layer to your Tag Manager settings in Unity.

[Winter.tsx.txt](https://github.com/Seanba/SuperTiled2Unity/files/10680784/Winter.tsx.txt)

**Comment by seanb-22ct** [comment]
Also, if you make me a contributor your Github project then I can just push up my changes in a separate branch.

**Comment by inspirsea** [comment]
Hi thanks for your swift reply and massive help. 
I send you an invite if you want to commit your changes. Will make sure to make the suggested changes. Will be realy interesting to see how this affects the import speed in the main project.

Thanks a bunch!

**Comment by seanb-22ct** [comment]
I've pushed up my changes to your GitHub under the `collision_refactor` branch. That should give you a good idea of the kind of changes I needed to make to make the importing go faster.

Once you complete cleaning on the collisions and put them into Ice or Water physical layers then you should be in good shape. Let me know if you have any questions.

**Comment by Seanba** [comment]
I'm closing this bug for now but if the issue resurfaces with new data I will look at it. Thanks.
