### ISSUE TITLE
Isometric tilemap has inverted sorting order when imported into unity

### ISSUE THREAD

**Issue by BossGrand** [Seanba/SuperTiled2Unity#239]
Hi I have a isometric tile map that looks like this in Tiled
![image](https://user-images.githubusercontent.com/2106699/232866813-3c42dd41-ec07-43ae-aca8-c8f094db621d.png)

When I import it into unity I get the following result. 

![image](https://user-images.githubusercontent.com/2106699/232866418-19a078d0-909d-4b82-8f2f-b34df82a1b6f.png)

If I manually invert all the sorting orders of the tiles generated by SuperTiled I get the expected layout.
I have a script that negates each sorting order of the tiles, effectively reversing the sorting order
![image](https://user-images.githubusercontent.com/2106699/232867841-d7171635-8a6c-418c-93a6-64fcd7dfabf2.png)

I couldn't find any setting or docs on how to fix this. Am I doing something wrong or is this a bug?

**Comment by seanb-22ct** [comment]
Hi again. It just occurred to me that you may need a custom `Transparency Sort Axis` in your graphics settings.

Here's some Unity documentation on it: https://docs.unity3d.com/Manual/Tilemap-Isometric-CreateIso.html

**Comment by BossGrand** [comment]
![IsometricTilesetBase](https://user-images.githubusercontent.com/2106699/232903902-bd8e0b1f-fd61-4245-a073-fe2148a9163a.png)

**Comment by BossGrand** [comment]
I tried different transparency sort axises but none worked. Here is a demo repo of my project
https://github.com/BossGrand/Iso-Demo

**Comment by seanb-22ct** [comment]
Hi again, @BossGrand. I had forgotten that Isometric maps, by necessity, are rendered as objects and not as tiles in a tilemap.
This is because Unity does not support the concept of an Isometric map.
(Staggered Isometric maps are supported though.)

In order to have the isometric objects rendered in the proper order you'll need reimport your Tiled maps with either the `Overhead Static` (probably best) or `Overhead Dynamic` layer/object sorting.

![image](https://user-images.githubusercontent.com/18538373/232933054-d3b55fc4-0127-480b-afdd-6f87be23ee23.png)

This should have been handled for you automatically but it is a bug I need to fix. In the meantime I hope that setting helps you out.

FWIW, depending on your game you may want to just go with the staggered isometric map option in Tiled.

**Comment by BossGrand** [comment]
Were you able to get it to work properly? I tried both overhead static/dynamic and neither seemed to have an effect.

As for the isometric, I want to make a Tactics game like Tactics Orgre :)

**Comment by BossGrand** [comment]
![image](https://user-images.githubusercontent.com/2106699/232941752-6c2db6f6-e3a8-4981-a89a-3e4cfa79b361.png)

**Comment by seanb-22ct** [comment]
Hi again, @BossGrand. Yes, I got it working. Keep in mind that you still have to use a custom sort axis.

![image](https://user-images.githubusercontent.com/18538373/233127031-f65e3f8f-af8f-4ea9-9216-502e19eaf2b9.png)

**Comment by BossGrand** [comment]
Oh awesome thank you so much!

**Comment by seanb-22ct** [comment]
I'm glad you got it working. I'm going to keep this issue open for now because there are a couple of small items I want to clean up on my end. I don't want the user to be confused like this when things are looking right. :)
