### ISSUE TITLE
How could I change tile in unity playing mode?

### ISSUE THREAD

**Issue by ankisme** [Seanba/SuperTiled2Unity#241]
For example, when player click the door, then the [closed door tile] change to [opened door tile], and how could I get UnityEngine.Tilemaps.TileBase of [opened door tile]?

Now I could not found a TilePalette of my importing .tmx or .tsx? And I check SuperTiled2Unity\Examples\Overhead, and chould not found TilePalette too.

It seems that I have misunderstandings about it.

Or is there any other way to do it?

**Comment by seanb-22ct** [comment]
Hi there, @ankisme. Sorry for the late reply.

Super Tiled2Unity doesn't use tile palettes since we are using Tiled Map Editor as the tool that places tiles on tilemaps.

When it comes to tiles that are "dynamic" in nature (i.e. you want to change them from one state to another) then I use an object (in an Object Group layer in Tiled) instead of a tile. That becomes a game object (with a sprite renderer) once imported into Unity and gives you greater control on how to modify it based on input or other game event.

Most users will also use Prefab Replacements for a case such as yours. This will take an object in Tiled and replace it with an instance of prefab. In your case that prefab will be your door game object.

You can read more about Prefab Replacements here: https://supertiled2unity.readthedocs.io/en/latest/manual/extending-the-importer.html

And this gitub project may serve as a guide too: https://github.com/Seanba/SuperPrefabReplacement

**Comment by ankisme** [comment]
OK, I will try an object to control it, I haven't use tiled object before, and thank you for replying.
