### ISSUE TITLE
Import issues 

### ISSUE THREAD

**Issue by LegionOnline** [Seanba/SuperTiled2Unity#244]
<img width="370" alt="ImportIssue" src="https://github.com/Seanba/SuperTiled2Unity/assets/123209907/91f196d0-9bc5-4196-befe-028ee82d128a">

Some reason I am getting these errors and I don't know why? I have imported everything..

**Comment by LegionOnline** [comment]
<img width="518" alt="image" src="https://github.com/Seanba/SuperTiled2Unity/assets/123209907/d80ef92a-b6f4-40b6-8f19-5f3625560062">

And when I open it in Tiled it looks fine.. and I did use Tiled2Unity at first and that worked fine.

**Comment by Seanba** [comment]
Hi there, @LegionOnline. I like your skull-themed map.

Your error is most likely due to either your `*.png` files not being imported into your Unity project or being imported into the wrong folder.

What is the full path of these two assets (in Unity)?

- `legion_overworld-map.tmx` file
- `Legion/Tilesets` folder?

Tiled is expecting your `Legion/Tilesets` folder to be 6 directories "back" from your TMX file.
And SuperTiled2Unity is expecting that folder (and its PNGs) to be imported into your Unity project.

If you provide the full (absolute) path of two assets I can probably figure out what you need to change to get this working.

**Comment by LegionOnline** [comment]
Thank you very much for your reply, 

For the legion_overworld-map.tmx file path:
<img width="420" alt="image" src="https://github.com/Seanba/SuperTiled2Unity/assets/123209907/320632e1-09d5-48c3-b9ee-076e29871552">

And for the Legion/Tilesets folder:
<img width="384" alt="image" src="https://github.com/Seanba/SuperTiled2Unity/assets/123209907/65ea7323-5599-4a74-8f92-7ca9136478bf">

**Comment by LegionOnline** [comment]
> Hi there, @LegionOnline. I like your skull-themed map.
> 
> Your error is most likely due to either your `*.png` files not being imported into your Unity project or being imported into the wrong folder.
> 
> What is the full path of these two assets (in Unity)?
> 
> * `legion_overworld-map.tmx` file
> * `Legion/Tilesets` folder?
> 
> Tiled is expecting your `Legion/Tilesets` folder to be 6 directories "back" from your TMX file. And SuperTiled2Unity is expecting that folder (and its PNGs) to be imported into your Unity project.
> 
> If you provide the full (absolute) path of those two assets I can probably figure out what you need to change to get this working.

Hello again,

I hope I am not too much of a bother, I am just really wanting to get this map into my game for a staff early access. I sent you the file paths and tried a few different things to get it working, I am very unsure what I am doing wrong so I am reaching out to you again. 

Thank you! ~ Tanzah

**Comment by Seanba** [comment]
Sorry, I've been busy. Yes, it looks like you've broken the "relative paths" between your map file and the tileset textures.

Are you using tileset (TSX) files? It looks like you're using embedded tilesets but I can't tell for sure.

If you are using an embedded tileset then probably the easiest thing to do is to edit your TMX file by hand so that it uses your textures in the new path you placed them when you imported them into Unity

So you would change something like this ...

```
<image source="../../../../../../Legion/Tilesets/legion_overworld-summer.png" ...
```

to this ...
```
<image source="../Tilesets/legion_overworld-summer.png" ...
```

Since you intend to have `Map` and `Tilesets` folders in the same `Legion` folder then the idea is to have your TMX file look for the texture "back one folder" (the `..`) then in the `Tilesets` folder. Does that make sense?

If you have your project up on github then I can change it for you this evening if you send me an invite.

**Comment by LegionOnline** [comment]
> Sorry, I've been busy. Yes, it looks like you've broken the "relative paths" between your map file and the tileset textures.
> 
> Are you using tileset (TSX) files? It looks like you're using embedded tilesets but I can't tell for sure.
> 
> If you are using an embedded tileset then probably the easiest thing to do is to edit your TMX file by hand so that it uses your textures in the new path you placed them when you imported them into Unity
> 
> So you would change something like this ...
> 
> ```
> <image source="../../../../../../Legion/Tilesets/legion_overworld-summer.png" ...
> ```
> 
> to this ...
> 
> ```
> <image source="../Tilesets/legion_overworld-summer.png" ...
> ```
> 
> Since you intend to have `Map` and `Tilesets` folders in the same `Legion` folder then the idea is to have your TMX file look for the texture "back one folder" (the `..`) then in the `Tilesets` folder. Does that make sense?
> 
> If you have your project up on github then I can change it for you this evening if you send me an invite.

Thank you, 

I'll see if I can figure it out with what you said, just incase I can not figure it out can I send you a zipped folder of the project via email or discord? it's not currently on GitHub. 

Once again, thank you for your help :)

**Comment by LegionOnline** [comment]
Sent
