### ISSUE TITLE
Does every object in object layer is imported as a collider by default ?

### ISSUE THREAD

**Issue by djnjbjb** [Seanba/SuperTiled2Unity#262]
I'm using version 2.1.1, I find that every object in object layer is imported as a collider by default, which is fine for me.

But I see a [post on 2021](https://discourse.mapeditor.org/t/problem-with-the-collisions/5178), which says "it(SuperTiled2Unity) will not automatically generate collision based on Objects".

I think what really happen in my Unity project is the actural fact - "In version 2.1.1, every object in object layer is imported as a collider by default". So the post must be outdated.

But I don't see anything about this on document.

So, I'm here just want to make sure that "In version 2.1.1, every object in object layer is imported as a collider by default".

**Comment by Seanba** [comment]
Hi there, @djnjbjb. My apologies for the very late reply. I think that comment ("it will not automatically generate collision based on Objects") is in reference to `Tile` objects. In that case you have to set up colliders in the `Tile Collision Editor` feature of Tiled in order for the tile to be imported with collision geometry.

Most other object types (`Rectangle, Ellipse, Polygon`) are imported as colliders.

The `Point` object type is not imported as a collider because it is just a point in space.

**Comment by djnjbjb** [comment]
Thanks a lot.
Very clear and detailed.
