### ISSUE TITLE
Import fails on Linux

### ISSUE THREAD

**Issue by Haelle** [Seanba/SuperTiled2Unity#263]
I'm on Unity2022.3.11 on Linux and using Tiled v2.1.1.

The zip file is unusable on Linux the files are all in the root directory and have `\` in their names where they should be in folders 😫

Can you make future version compatible for Linux ?

This script fixed the folder for me (and the package works) : 

```sh
#!/bin/bash

DIR="/path/to/SuperTiled2Unity"
find "$DIR" -type f | while read -r file; do
    newpath=$(echo "$file" | tr '\\' '/')
    mkdir -p "$(dirname "$newpath")"
    mv "$file" "$newpath"
done
```

P.S: I created an issue when noticing it wasn't the same problem as I though [here](https://github.com/Seanba/SuperTiled2Unity/issues/253#issuecomment-1894647578)

**Comment by Seanba** [comment]
Hi there, @Haelle. Sorry for the late reply. I've changed the deployment script so that creates the zip with 7Zip instead of the Windows Powershell Compress-Archive command. This should make it so that future versions of the ST2U zip can be opened by Linux users. I'll post again here when the next version is available.

**Comment by Seanba** [comment]
Hi again, @Haelle. Version 2.2.0 of Super Tiled2Unity should have this fixed. Please let me know if the issue remains and thanks for the bug report.
