### ISSUE TITLE
Transparent Color Not Applying

### ISSUE THREAD

**Issue by JoshMayberry** [Seanba/SuperTiled2Unity#270]
In Tiled, I can set a color as being transparent.
![image](https://github.com/Seanba/SuperTiled2Unity/assets/11482252/b8b06d6c-190d-438c-a7f1-4596524a71b4)

But, when the files are imported- the transparency is not being applied.
![image](https://github.com/Seanba/SuperTiled2Unity/assets/11482252/c00fdca9-8baf-4f78-b6d5-4e432fc55453)

**Comment by Seanba** [comment]
Hi there, @JoshMayberry. Because of the relationship between materials and shaders in Unity compared to tilesets and textures in Tiled there isn't a way that ST2U can have this "just work" out of the box.

However, you can override the default material that ST2U assigns to every Tilemap in a TMX file. You could make your own material and shader combination that treats a specific color (like cyan in your example) as transparent and use that here.

![image](https://github.com/Seanba/SuperTiled2Unity/assets/6980630/98fc544f-cd0d-46cb-9ac7-36e17cf9f85b)

You may also want to use the `Material Matchings` feature if you only want to use specific materials with specific Tiled map layers. Hope this helps.
