### ISSUE TITLE
Negative Y coordinates in Tilemap

### ISSUE THREAD

**Issue by demso** [Seanba/SuperTiled2Unity#274]
Why does my Tilemap has negative Y coordinate as shown on screenshot? Expected coordinates (5, 4)

![image](https://github.com/Seanba/SuperTiled2Unity/assets/41340027/4510d49e-7ba9-4b4b-937a-b907404f621b)

**Comment by seanb-22ct** [comment]
Hi there, @demso. This is because Tiled and Unity employ different coordinate systems. I admit it's annoying to having negative values but I wanted to keep the origin of the map at (0, 0) while have the map increase in height downwards (like in Tiled).

![image](https://github.com/Seanba/SuperTiled2Unity/assets/18538373/736b06d6-4b1d-461c-9464-d900c9be8db2)

![image](https://github.com/Seanba/SuperTiled2Unity/assets/18538373/7d49dbcc-8f9f-4da8-a8a3-5ffcf43c4276)

**Comment by demso** [comment]
Thanks for clarifying!
