### ISSUE TITLE
Super Tiled2Unity keeps freezing Unity

### ISSUE THREAD

**Issue by richicon** [Seanba/SuperTiled2Unity#29]
I just upgraded to Unity 2018.3, and at the same time upgraded from Tiled2Unity to SuperTiled2Unity.

I have a major issue though in that SuperTiled2Unity keeps freezing Unity when running the game, when exiting run mode and when opening the Levels folder in the inspector. It isn't a crash as control returns after a few minutes.

So now it takes a couple of minutes before the game will run in the edior - I click the PLAY button, it starts OK, the level music starts playing, etc, but visually just a black screen while it seems to be processing the level. A couple of minutes later it completes whatever it was doing and the level only then becomes visible and you can play.

I have over 20 TMX level files in the Levels folder - and again, if I click on that folder in Unity, it freezes for a few minutes.

Right now it is unusable like this.

The only issue I can see, although I don't know if it has any bearing, is that the TMX files have warnings stating:

"Tileset 'tilesetname' is an embedded tileset. Exported tilesets are preferred."

All the levels were created with the default 'New Tileset' option within Tiled, whereby I select a PNG tileset.

Help! :)

**Comment by Seanba** [comment]
Hi @richicon. If you are using embeeded tilesets then I would expect the import process to take some time as tileset texture atlases are being created for every tileset in every map.

However, that should only be an issue when you are importing, not when entering/exiting run mode. Is there any messages in the console window? If you send me your Unity project I can probably take a look some time this weekend.

**Comment by richicon** [comment]
Thanks Sean

I did a further test - running the level now seems quicker - under a minute now, but if I click on the Levels folder in the inspector - it takes 4 minutes from clicking the folder icon until it shows the contents.

There are 28 TMX files in that folder, each one uses about 10 tilesheets, although several of these are individual collision tiles with just one tile per sheet. The other sheets are 16x16 pixel tile sizes, with a typical sheet size of 512x512 pixels. Map sizes are between 128x128 tiles and 256x256 tiles (16x16 pixel tile size).

Any ideas what I can do to reduce this freeze on clicking on the Levels folder? I considered putting each level into a sub-folder, but ideally I'd rather not.

**Comment by Seanba** [comment]
Hi again, @richicon. Do you mind exporting your project as a Unity Package and sending it to me? My email: sean@seanba.com

**Comment by Seanba** [comment]
Hi again, @richicon. Here's what I found:

- Your imported TMX assets, combined, have 246,095 objects in them. Unity treats each of these as a separate file (even though they are 28 assets with may sub-assets in them). So, in effect, Unity is building a folder treeview with nearly a quarter million items each time you select the `Levels` folder and that's what's eating up your 4 minutes.
- Most of this repeated data because each TMX file is using internal tilesets.
- Using TSX references instead of internal tilesets was a huge improvement. There is no noticeable slowdown when selecting the `Levels` folder anymore. However, your `Tiles` folder, which now contains your tilesets, has some 60,000 items in it. However, it only takes about 10 seconds to select that folder.
- Note that this is also be a _significant_ improvement when you are resaving (and reimporting) any changes you make to your TMX files now since they won't be responsible for rebuilding tilesets.

I'll email you a Unity package with the TMX and TSX file changes I made. I recommend opening them in a new project first though just to make sure I don't incorrectly overwrite your work.

Oh, and btw, I put up a new version of SuperTiled2Unity (1.1.9) that does a little better job with import dependencies. You may want to grab that too.

**Comment by richicon** [comment]
Oh wow – that is incredible.

 

Thank you so much for taking the time to look at the project and to fix those levels. Seriously – that is just amazing, cheers 😊

 

I’m back to work tomorrow so I’ll get those in first thing.

 

If I may ask one further question – am I doing anything silly with the levels – I tried to design them with logical layers, but is there a more optimal approach I should be taking, such as fewer layers?

 

Richard
