### ISSUE TITLE
Some questions and suggestions concerning sprite import and atlas packing

### ISSUE THREAD

**Issue by SharlatanY** [Seanba/SuperTiled2Unity#36]
Hello there!

I have a few suggestions and questions concerning importing sprites and also about packing them into an atlas. Here we go:

1. **Would it be possible to add an option to **not** import sprites where every pixel is 100% transparent (alpha = 0)?** I tried around a bit with discarding them but since your indexing them and use that index in various places, I can't just add a fix in one file and wouldn't want to do a bigger refactoring which I will have to try to merge again every time you publish an update of ST2U.
**Reason**:
Sometimes you realize that you don't need some sprites after all and delete them from your sprite sheet. There are good tools out there to repack your sprite sheets that would make this task easy. The only problem is, changing a sprite sheet that's used for a *.tsx file, which in turn is already used by a Tiled map, is a _huge_ pain. Because of that, you just delete the sprites in the source picture (=make the pixels they were at transparent). Since all sprites are imported, even the ones that are 100% invisible, this leads to two problems: Firstly, the project gets cluttered with a lot of sprites that are never used. Secondly, since those transparent sprites are also packed into the atlas, This can increase the required atlas size or amount of atlases a lot, which in turn increases build size by a lot. If you have big tiles/and or small atlases, you sometimes can even end up with an atlas that _only_ contains transparent sprites but of course uses up just as much space as if it was filled with "real" tiles.
2. **Would it be possible to expose some more atlas functions like the compression quality used?** Not super important, just nice to have.
3. **Can you please explain to me how the atlas packing works?** It somehow works, the results are just a bit confusing to me and I'd love to understand why things are the way they are.
Here's an example atlas generated by ST2U: 
![image](https://user-images.githubusercontent.com/12735825/52532877-cd235800-2d2b-11e9-9e40-be96676bb3d2.png)
The source tiles are 32x32 pixels and as you can see, the texture is 256x256.
However, there are only 7 tiles per column/row but 256/32 = 8, so, theoretically 8 tiles should fit. When I make a screenshot and count the pixels, the tiles seem to be 36x36 each. This not only explain, why only 7 fit but also why there's the pink 4px border that would be the reminder of 256-7x36.
On closer inspection, it seems like you're doubling the 2 outermost pixels of every border of the tile and adding them again as new border, at least inside the atlas. When looking at the tilemap in the scene editor or during runtime, you can't see it anymore. Is that some image sorcery to prevent seaming issues? Would you mind explaining, how this works?

Thanks a lot and have a great Sunday!

**Comment by AberrantWolf** [comment]
I can answer #3 at least. There's a bit of uncertainty 3D rendering where, unless you're being REALLY careful about your camera position and viewport size, you can sometimes end up rendering a pixel that's outside of the bounds of the texture UVs (texture mapping is sent to the GPU using floating-point coordinates, not pixel boundaries, so there's a bit of imprecision that you can't escape easily).

What this means is that as your camera moves smoothly, you can end up seeing a pixel that's colored from a neighboring tile due to the imprecision of raster rendering. The solution to this is to duplicate the outer pixel of each tile while keeping the actual mapped region within those. Now, even if there's some imprecision in the UV coordinates, you'll always see the color you expect to see along all of the tile edges! :)

**Comment by SharlatanY** [comment]
Wow, that's interesting! Thanks for the explanation!

**Comment by Seanba** [comment]
Hi there, @SharlatanY.

I think #1 and #2 are good ideas worth pursuing. Can you please make separate requests for each so I can track progress against them? Fair warning: I'm currently retooling isometric support and adding an option that automatically replaces Tiled Objects with Unity Prefabs so it may take some time for me to get to these.

@AberrantWolf answered #3 well. The sprite atlases are a way of eliminating annoying seams that would otherwise be present in your imported maps. Unity has some support for atlases but I'm afraid the API is not fully-formed yet for people like me to use so I've built my own atlas tools into SuperTiled2Unity.

**Comment by SharlatanY** [comment]
Hey @Seanba 

Thanks for getting back to me so quickly!

As you suggested, I opened #37 and #38. Thanks for considering!
And no worries, it really doesn't hurry. I'm working with ST2U and always come back here and suggest something when I discover a use case where I think that a) the tool could save me a lot of time/headaches  with a new feature and b) said feature might be interesting to other people too. But there's really no hurry but thanks for the warning! 

And the "Replace Tiled objects with Unity Prefabs" sounds like a great idea! I have several custom importers that exactly do this and I wouldn't mind getting rid of them!

Since I opened the other issues for the feature requests and all my questions are answered, I'll close this issue now.

Thanks again and have a nice day!
