### ISSUE TITLE
Animations having severely reduced speeds when in Unity

### ISSUE THREAD

**Issue by VladDerptastic** [Seanba/SuperTiled2Unity#4]
At this point it feels like I should apologize for posting yet again.

I have a bunch of animated Tiles for various objects/effects but the easiest to see example would be the water animation. 
The transition between tile states is set to 100 (the default) in Tiled.

This is how it appears in TIled (ignore any jitters at the bottom):
![intiledsmall](https://user-images.githubusercontent.com/17119930/46611633-91267f00-cb0e-11e8-8bca-646eb2b85ed8.gif)

This is how it appears in Unity (again, ignore any jitters at the bottom):
![inunitysmall](https://user-images.githubusercontent.com/17119930/46611699-c92dc200-cb0e-11e8-97aa-ba6b9ecb14ba.gif)

**Comment by Seanba** [comment]
Hi Vlad, no apologies needed. I appreciate you putting SuperTiled2Unity through its paces.

Animations are a problem at the moment but I think I came up with a solution. Sadly, I won't have time to work on them for another week. :)

Are the timing on your frames all the same in Tiled? If so, you can set the Animation Frame Rate in the importing settings of your TMX file in the inspector. For instance, if all your frames are 100ms then set the Animation Frame Rate to 10fps. The default is 1fps which is why your animations are so slow.

If your frames use variable timings then you'll have to wait for my fix. I'll update this bug when I have it ready. Thanks.

**Comment by VladDerptastic** [comment]
Yes, they are with the same timing. 
I tried the workaround and the water is as pretty as hoped for. Thank you. =)

Since you're aware of some problems different timings give, and my problem was for animations with the same pace (for which your workaround did the trick), should I close this issue? 

And, as a side note just to clarify, this would speed up all my animations, by the same rate, right? So as long they are with the same timings (e.g all transitions in an object are at 300ms, or at 200ms), the speed up should be equal for all?

**Comment by Seanba** [comment]
Let's keep the issue open for now. I'll close it when I deliver the feature that allows for variable frame timings.

To answer your other question: Yes, that would speed up all your animations.

Thanks again,
Sean

**Comment by Seanba** [comment]
SuperTiled2Unity 1.1.0 was just published which uses the duration of animation frames set up in Tiled's Animation editor. Note that we are forced to have the same FPS setting that is used by *all* maps in your project. By default, this setting is 20fps which works well for animations that are multiples of 50ms in Tiled.

https://seanba.itch.io/supertiled2unity/devlog/53226/supertiled2unity-version-110

**Comment by VladDerptastic** [comment]
I'll have the possibility to test it, in a day or so.

**Comment by VladDerptastic** [comment]
Well that was a long "day or so", wasn't it? Sorry about that. In any case. the FPS setting fix is working perfectly for me.

**Comment by Seanba** [comment]
No worries, Vlad. I'm glad it worked for you.
