### ISSUE TITLE
Tile properties

### ISSUE THREAD

**Issue by Heishe** [Seanba/SuperTiled2Unity#47]
The importer supports map properties (defined for a tilemap as a whole), but does the importer support tile properties? 

These are vitally important - if anyone is going to use Tiled to place gameplay-specific stuff (like event triggers, spawn points, and so forth) it'll probably be done using tiles with individual tile properties. I mean the ones you get when editing the tileset and clicking on a tile:

![image](https://user-images.githubusercontent.com/2046189/53741559-f9e40e80-3e96-11e9-9159-1e6001dfabb9.png)

**Comment by Seanba** [comment]
Hi there, @Heishe. When it comes to dynamic behavior I think in most cases you are better served using objects on an `Object Layer` instead of checking for custom properties at a specific tile location.

However, you can get to these custom properties in script if you wish. I have put an example of up on my Github: https://github.com/Seanba/ST2U_TileProperties

The key is to call the Unity's `Tilemap.GetTile()` method ([see docs](https://docs.unity3d.com/ScriptReference/Tilemaps.Tilemap.GetTile.html)). That returns a `TileBase` instance that can be cast to the `SuperTile` type which contains all the custom properties for that tile.

Below is the code I use in that demo linked above to get the value of a custom property named `terrain-type`:

```cs
var tilemap = GameObject.FindGameObjectWithTag("TerrainMap").GetComponent<Tilemap>();
var worldPosition = gameObject.transform.position + (Vector3)m_Offset;
var cellPosition = tilemap.WorldToCell(worldPosition);

// Get the tile at the given cell position
if (tilemap.GetTile(cellPosition) is SuperTile tile)
{
    // Report to our UI which tile we're standing on
    var text = GameObject.FindGameObjectWithTag("TileTypeText").GetComponent<TextMeshProUGUI>();
    text.text = tile.GetPropertyValueAsString("terrain-type", "unknown");
}
```

**Comment by Heishe** [comment]
@Seanba That's awesome! Thanks for the work.
