### ISSUE TITLE
Importing process is too slow.

### ISSUE THREAD

**Issue by Titianzi** [Seanba/SuperTiled2Unity#48]
I want to import a big map into Unity.
Size of map is 256x512 (isometric staggered). It has 16384 x 8192 pixels. I split it to 64 tile sets, and each tile set has 1024 tiles, 64x32 pixels for each tile. 
It takes me nearly 2 hours to waiting importing process.  It's too slow!!!
![image](https://user-images.githubusercontent.com/36870979/54070542-1bc90100-429c-11e9-93cb-9f78cd4e52cd.png)
It takes much time and use much CPU time in generating metadata of .tsx files.
Besides, after map imported, any operations about the .tsx file will make Unity die for 20 seconds, include open folder with .tsx
Other Information:
Unity Version: 2018.3.6f1
Super Tile2Unity version: 1.2.4
Tiled Editor Version: 1.2.2
Operation System: Windows 10 10.0.17134
CPU: Intel Core i7 6700HQ

**Comment by Titianzi** [comment]
Maybe I have found the reason... When tsx files first importing, it will generate sprite atlas in default. But I have too many tiles in tilesets. Well, the question is: how can I  stop it generate sprite atlas when I first import it?

**Comment by Seanba** [comment]
Hi there, @Titianzi. What do you mean by too many in tilesets? Is SuperTiled2Unity warning you that they won't fit is the sprite atlas?

I had noticed with an earlier version that the creation of a sprite atlas was very slow but that should be fixed now. Could you export your project as a Unity Package and send it to me? (sean@seanba.com)

Lastly, I'll look into a way to give you a chance to disable sprite atlases by default so that the first import doesn't take so long.
