### ISSUE TITLE
Error importing .tmx

### ISSUE THREAD

**Issue by PlonkaGames** [Seanba/SuperTiled2Unity#63]
Hi
I imported the .ts, png and related tmx filed and I got the issue shown on image 1. 

I then checked the sorting layers - image 2 - and that showed my layers I use. 

I re-imported and got the error show on image 3.  

I then deleted the level6.txm and re-imported it - and got the error show on image 4 ( same as 3 I think ).

I'm hoping I can get this to work as I want to use Templates ( which I hope will work with ST2U to Unity ).

Thanks in advance
Frank

**Comment by PlonkaGames** [comment]
/Users/Cacker/Downloads/Level6 ST2U error 4.png
/Users/Cacker/Downloads/Level6 ST2U error 3.png
/Users/Cacker/Downloads/Level6 ST2U error 2.png
/Users/Cacker/Downloads/Level6 ST2U error 1.png

**Comment by PlonkaGames** [comment]
Images

**Comment by PlonkaGames** [comment]
Images won't attach

**Comment by PlonkaGames** [comment]
Image 1 - says "Sorting Layers are missing in your project settings.  Open Tag Manager add them and reimport. 

background

image 2 - just shows my list of Sorting Layers which include standard and the layer names in my project

image 3 - says Unknown error encountered. Please report as bug.  Stack track is in the console output.  

An element with the same key already exists in the dictionary.

image 4 - same as 3

**Comment by seanb-22ct** [comment]
Can you email me those images? I'll add them to this bug report. (sean@seanba.com)

If possible it might be a good idea to email me your project as a Unity package (and zip up your `ProjectSettings` directory too so I get your tag manager settings)

**Comment by seanb-22ct** [comment]
The "dictionary" error was fixed in an earlier version of SuperTiled2Unity. Other issues seem to stem from using Unity 2018.2 (SuperTiled2Unity requires 2018.3).

Upgrading both Unity and SuperTiled2Unity should fix your problems. Be aware that many people have reported problems upgrading Unity to version 2018.3 (their Package Manager is missing). This is unrelated to SuperTiled2Unity but I've had this problem before.

https://forum.unity.com/threads/package-manager-is-missing.557854/
