### ISSUE TITLE
String WhiteSpace Issue

### ISSUE THREAD

**Issue by firebellys** [Seanba/SuperTiled2Unity#91]
Using `SuperTiled2Unity.1.5.8.unitypackage `

https://github.com/Seanba/SuperTiled2Unity/blob/facd3d007cabe102deb466fdf94fefef05b62f8b/SuperTiled2Unity/Assets/SuperTiled2Unity/Scripts/Editor/Importers/TmxAssetImporter.TileLayer.cs#L366

This caused an error for me because for some reason, I don't see `IsNullOrWhiteSpace` as a valid method, `IsNullOrEmpty` works though.

<img width="693" alt="Screen Shot 2019-08-30 at 10 06 34 PM" src="https://user-images.githubusercontent.com/577101/64059487-7cae0380-cb72-11e9-897f-43e1bbb73118.png">

**Comment by Seanba** [comment]
Hi there, @firebellys. This sounds like an issue with the Mono library your version of Unity is using. I'd like to replicate your problem so I have a better sense of the best fix (or helpful error message).

- What version of Unity are you using?
- What OS are you using?
- What do your `Project Settings -> Player -> Configuration` settings look like?

![image](https://user-images.githubusercontent.com/6980630/64067119-fed90f00-cbe8-11e9-9511-43f4f1cac85e.png)

Usually these types of errors are fixed by choosing an upgraded scripting backend or API compatibility level but I can play with those settings in my development environment without getting your error.

**Comment by Seanba** [comment]
I was able to reproduce your error using a Unity 2018.3 project with a deprecated .NET runtime:

![image](https://user-images.githubusercontent.com/6980630/64067255-58423d80-cbeb-11e9-8941-94c824ddf532.png)

I'll put a fix that handles legacy .NET frameworks soonish but in the meantime if you switch your project to use `.NET 4.x Equivalent` instead then it should fix up this error for you.

**Comment by Seanba** [comment]
I just pushed up a new version of SuperTiled2Unity that fixes this issue.

https://seanba.itch.io/supertiled2unity/devlog/97712/supertiled2unity-version-159

 It's generally a good idea to upgrade your Scripting Runtime Version but I don't want ST2U to be the library that breaks things if you keep with the old runtime. :)
