### ISSUE TITLE
Impossible to import some maps on Unity

### ISSUE THREAD

**Issue by Bwaude** [Seanba/SuperTiled2Unity#93]
Hi !
Firstly I want to thank you for the program you made. It's increadible and help me a lot. 

Nevertheless I have an error that I don't understand. I can't import certain .tmx files whatever version of Unity I took. When I try to import them in the project folder, Unity freezes (The task manager told me Unity stops working). Whereas the other maps work perfectly ...

Can you help me identifying the problem ? 
Thank you and have a good day !​

**Comment by Seanba** [comment]
Hi there, @Bwaude. If you send me your map and any tilesets or textures it depends on then I can try to import the map myself.

Usually, maps that are slow to import are rather large (hundreds or thousands of tiles wide and high) and have collision geometry that creates a lot of collision gaps. A quick thing to try is to use the `Infinite` map setting (in Tiled) as this breaks your map down into smaller chunks.

**Comment by Bwaude** [comment]
Hi !
Okay ... Hum ... Actually, you were right : the Infinite map setting makes them work !
For them that have the same question as me : My maps worked before I recreated them with the fabulous setting, I just changed the colliders on the .tsx and then Unity went crazy.
I use Unity 2018.3.14f1 and SuperTiled2Unity 1.5.5. I check with the last version (1.5.10) and it works too.

Thank you @Seanba for your precious help (And sorry for my email) !

**Comment by Seanba** [comment]
Hi again, @Bwaude, I took the liberty of checking out some of your tilesets and although using the `Infinite` setting is helpful for you you will probably be better served to fix some of your collisions in the Tiled Collision Editor.

In particular, you are not using any "Snapping" so your collision geometry is not on pixel boundaries. So although a collision polygon may look right in Tiled ...

![image](https://user-images.githubusercontent.com/6980630/64979647-bc1c6580-d87d-11e9-8948-3a877c8eda39.png)

... as you zoom in you'll see that there are some small gaps ...

![image](https://user-images.githubusercontent.com/6980630/64979681-cdfe0880-d87d-11e9-9635-67eb70f56c15.png)

... and this causes the import process to slow down because collision polygons are not lining up nicely against each other in your map.

A quick fix for this is to make sure you have snapping turned on in Tiled ...

![image](https://user-images.githubusercontent.com/6980630/64979759-fede3d80-d87d-11e9-85be-d5363e30d806.png)

Hope that helps.
