### ISSUE TITLE
Collision TMX Orthographic Map, collision on specific tiles within a tileset.

### ISSUE THREAD

**Issue by Langerz82** [Seanba/SuperTiled2Unity#96]
Hey Sean, 
I got a tmx dungeon file generated and I want to make specific tiles within a tileset to collide with my movable character sprite (the example in SuperTiled atm). In the tileset tsx file I have two custom properties, one called "c" that stands for collision and "v" that stands for the foreground layer. Anyway how can I generate a collide square for each matching tile that placed within any layer? It would be great to dynamically generate joined polygon collision on the basis of the collidable tiles at the press of a button if this is currently not possible perhaps this is something I can implement and do a PR for you. I just need some pointers on what to code for the above case. Cheers man and keep up the good work!

Kind regards
Langerz

**Comment by Langerz82** [comment]
Yo, I have completed some code to get the tile collisions. But the Player is not colliding with the Layer.
Here is the demo project: https://1drv.ms/u/s!AnIJz4-QxGiaduI04fRP6DAniZ8

**Comment by Seanba** [comment]
Hi there, @Langerz82. You don't want to make changes to the SuperTiled2Unity importers as I often make updates.

What you want to accomplish with colliders is already supported out of the box. You add colliders to each tile in the Tiled Collision Editor and use a custom property named `unity:layer` to control which physics layers is applied to it in Unity. All colliders on the same layer will be automatically grouped together for you.

![image](https://user-images.githubusercontent.com/6980630/66146948-682ab400-e5d3-11e9-873e-54bd82988fad.png)

![image](https://user-images.githubusercontent.com/6980630/66146994-7ed10b00-e5d3-11e9-9ee4-7847b4d64b2c.png)

Make sure to have snapping turned on in Tiled so that your colliders fall on pixel boundaries (otherwise you may end up with gaps in your colliders).

![image](https://user-images.githubusercontent.com/6980630/66147127-cd7ea500-e5d3-11e9-9e00-e9c07bd5dadf.png)

Your map is fairly big so you're likely to get some performance gains by marking it as `Infinite`. This will break your map up into smaller chunks for you ...

![image](https://user-images.githubusercontent.com/6980630/66147197-f868f900-e5d3-11e9-97e9-bb8e344fe07d.png)

Lastly, for some reason you have two versions of SuperTiled2Unity in this project (with the second named Tiled2Unity?). You should clean that up so that you only have one clean install.

**Comment by Seanba** [comment]
@Langerz82 I'm going to close this issue for now but if you're still have an issue with colliders let me know. Thanks.
