### ISSUE TITLE
Importing Error

### ISSUE THREAD

**Issue by kumakoko** [Seanba/SuperTiled2Unity#99]
When I imported SuperTiled2Unity.unitypackage (**version 1.6.1** ) in Unity **2018.4.9.f1**.There was a error :

**Assembly has reference to non-existent assembly 'GUID:06e56dbbb8dec4d43a0b85b0fe0dd0ca' (Assets/SuperTiled2Unity/Scripts/Editor/SuperTiled2UnityEditor.asmdef)**

And what is the assembly  referenced by SuperTiled2UnityEditor.asmdef and how to deal with this problem?

**Comment by Seanba** [comment]
Oh boy. I wonder if Unity 2018 doesn't support assembly definitions that are not in the root? I'll look into that.

**Comment by Seanba** [comment]
Version 1.6.2 of SuperTiled2Unity fixes this error. 

https://seanba.itch.io/supertiled2unity/devlog/103090/supertiled2unity-version-162

**The boring details**: Unity 2019 allows for assembly definitions to be referenced by GUID. In order to support Unity 2018 I'm now using file name references instead.

Thanks for the bug report.
